spring:
  mongodb:
    application: router
    host: localhost
    port: 27017
    database: router
    login: admin
    password: admin
  admin:
    username: admin
    password: admin
server:
  port: 8080

